/*
 *  Sistema de Control de Asistencia y Notas
 *  111Mil Programadores
 */
package vistas;

/**
 *
 * @author PC HP
 */
public class vistaPantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPantallaPrincipal
     */
    public vistaPantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnajustes = new javax.swing.JButton();
        btnalumno = new javax.swing.JButton();
        btnprofesor = new javax.swing.JButton();
        btnasistencia = new javax.swing.JButton();
        btnnotas = new javax.swing.JButton();
        btnayuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        btnajustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconConfiguración.png"))); // NOI18N
        btnajustes.setText("Ajustes");
        jPanel1.add(btnajustes);

        btnalumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconEstudiante.png"))); // NOI18N
        btnalumno.setText("Alumnos");
        jPanel1.add(btnalumno);

        btnprofesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconProfesor.png"))); // NOI18N
        btnprofesor.setText("Profesores");
        jPanel1.add(btnprofesor);

        btnasistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconAsistencia.png"))); // NOI18N
        btnasistencia.setText("Asistencias");
        jPanel1.add(btnasistencia);

        btnnotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconCalificaciones.png"))); // NOI18N
        btnnotas.setText("Notas");
        jPanel1.add(btnnotas);

        btnayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconAyuda.png"))); // NOI18N
        btnayuda.setText("Ayuda");
        jPanel1.add(btnayuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajustes;
    private javax.swing.JButton btnalumno;
    private javax.swing.JButton btnasistencia;
    private javax.swing.JButton btnayuda;
    private javax.swing.JButton btnnotas;
    private javax.swing.JButton btnprofesor;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
